### ISSUE TITLE
Add comments for godoc support

### ISSUE THREAD

**Issue by tehbilly** [hypersleep/easyssh#2]
This looks to be a very useful package, however I think usage examples and code documentation should support standard [go documentation](http://blog.golang.org/godoc-documenting-go-code) formats.

**Comment by weekface** [comment]
+1

**Comment by hypersleep** [comment]
Sounds good idea! I'll try to bring documentation under go standart in few days.

P.S. Thank you for first issue! Other issues and pull requests are welcome :)

**Comment by hypersleep** [comment]
Guys, i've added documentation. My English is bad in some moments therefore edits are welcome :)
