### ISSUE TITLE
API Stability

### ISSUE THREAD

**Issue by sorcix** [hypersleep/easyssh#24]
We had to change a lot of code because the recent change to `Run`. Is the API of easyssh considered stable, or should we change to a different package to prevent issues like these in the future?

Could you consider adding version branches and use something like gopkg.in to provide a stable package while allowing you to make breaking changes?

**Comment by hypersleep** [comment]
@sorcix you can use v0 version of this package as in this example: https://github.com/hypersleep/easyssh/blob/master/example/run.go

**Comment by sorcix** [comment]
Thanks, but it looks like that's not go-gettable.

Trying with `gopkg.in/hypersleep/easyssh.v0`, that may work.
