### ISSUE TITLE
Versioned Releases

### ISSUE THREAD

**Issue by Jmeyering** [hypersleep/easyssh#7]
Any chance you could version a release of this package? Would like to use gopkg.in to retrieve but there aren't any releases atm.

**Comment by hypersleep** [comment]
Hi Jared! Thank you for your advice. I think it's good idea. I'll freeze a current repo state in new "v0" branch and all new features will be added in "v1" branch.

**Comment by Jmeyering** [comment]
Awesome thanks!

**Comment by Jmeyering** [comment]
No word on this?

**Comment by hypersleep** [comment]
@Jmeyering  Sorry. Last two month i have been very busy by my current job project. Now it's done if you interested.
